max_width = 100
unstable_features = true
group_imports = "StdExternalCrate"
imports_granularity = "Module"
wrap_comments = true
normalize_comments = true
reorder_impl_items = true
format_strings = true
newline_style = "Unix"
